name = "v3t"
license = "MIT"
licenselink = ""
description = "A simple open source theme for publishing with hugo"
homepage = "https://github.com/daeshu/v3t"
tags = ["blog", "simple", "dark", "minimalist", "fast"]
features = ["blog", "simple", "dark", "minimalist"]
min_version = "0.57.0"

[author]
    name ="niel"
    homepage = ""
